name: Manual CI (armv7hl@3.0.2)

on:
  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

defaults:
  run:
    # Note that 'bash' provides -o pipefail, in contrast to the default (i.e., unspecified, which also uses bash) or 'sh',
    # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: sh

# See, e.g.: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ci-${{ github.ref_name }}
  # 'false' (default) allows for two concurrent runs, one executing and one freshly enqueued; 'true' for only one; no 'concurrency:' defined for multiple.
  cancel-in-progress: true

jobs:
  SDK-302:
    runs-on: ubuntu-22.04
    env:
      # For the available docker images, see https://github.com/CODeRUS/docker-sailfishos-platform-sdk
      RELEASE: 3.0.2.8
      # Do not wait up to the default of 10 minutes for network timeouts in a workflow which runs ca. 10 minutes.
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # Caching Docker images is not ready yet, see 
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/…
    #    key: cache

    - name: Prepare
      run: mkdir RPMS

    - name: Build armv7hl on ${{ env.RELEASE }}
      uses: coderus/github-sfos-build@old-stable
      with:
        release: ${{ env.RELEASE }}
        arch: armv7hl

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results_SFOS${{ env.RELEASE }}+
        path: RPMS/
